version: '3.4'
# with docker-compose 2.1 depends-on with condition like service_healthy
# since docker-compose 3 depends-on with no more condition
# since version 3 , needs to ajust healthcheck/interval,timeout,retries
# healthcheck/start_period depuis v4.3

networks:
  mynetwork:
    external: true
    
services:
      
  backend-api-devise:
    build : ./backend-api-devise
#   image: xyz/devise-api
    container_name: backend-api-devise
    environment:
      PORT : 8282
    networks:
      mynetwork:
        aliases:
          - backend-devise.api.host
          - backend-devise.api.service
    ports:
      - "8282:8282"