version: '3.4'
#NB: -port: host_port:container_port

networks:
  kafka-net:
    driver: bridge
  mynetwork:
    external: true
    
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    networks:
      - kafka-net
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - 2181:2181
      - 8888:8080
  
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    networks:
      - kafka-net
      - mynetwork
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'

